version: '3.7'

services:
  car-buddy:
    image: "princeigwe/car-buddy"
    ports:
      - "80:3000"
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      RDS_USERNAME: ${RDS_USERNAME}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DB_NAME: ${RDS_DB_NAME}
      RDS_HOSTNAME: ${RDS_HOSTNAME}
      RDS_PORT: ${RDS_PORT}
    depends_on:
      - postgres
      - mongo
  

  postgres:
    container_name: car_postgres
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      # POSTGRES_HOST: ${DB_HOST}
    # ports:
    #   - 5432:5432
  

  mongo:
    container_name: car_mongodb
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGOROOTUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGOROOTPASSWD}
    
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
    ports: 
      - '27017-27019:27017-27019'